#
#  Date and  intial time
#
yeari    = _START_YY_
yearf    = _END_YY_
iniyear  = 1950
nmonths  = 12
imonth   = 1
iday     = 1
ihour    = 0
#
#   Grid spacing
#
nz = 53
nsoil = 4
nlon = 424
nlat = 412
xoffset = 10
yoffset = 10
#
# Location of the files 
# dir  - location of the WRF files
# dir2 - location of the output files
#
dir = '/ec/res4/scratch/ptrt/wrf_run/'
dir2 = '/ec/res4/scratch/ptrt/ssp370/output/'
#
geog = 'geo_em.d01'
wrffile = 'wrfxtrm'
#
dom = '1'
outdom = '_EUR-12_MPI-ESM1-2-HR_ssp370_r1i1p1f1_IDL-FCUL_WRF451Q_v1-r1_'
#
