cordex
#
verbose 2        level of screen output: -1(none) 0(a bit) 1(a lot) 2(all)
#
#  Date and  intial time
#
yeari   _START_YY_
yearf   _END_YY_
iniyear  1950
nmonth    12
imonth     1
iday       1
ihour      0
#
#   Grid spacing
#
nz        53
nsoil      4
nlon     424
nlat     412
xoffset   10
yoffset   10
#
# Location of the files 
#
dir     ''
dir2    ''
#
geog    'geo_em.d01'
wrffile 'wrfxtrm'
#
dom          '1'
outdom       '_EUR-12_MPI-ESM1-2-HR_ssp370_r1i1p1f1_IDL-FCUL_WRF451Q_v1-r1_'
#
dexp_id      'ssp370'
dexp         'gap-filling scenario reaching 7.0 based on SSP3'               
